[tox]
envlist = docs
skipsdist = True

[testenv:docs]
description = Build Sphinx documentation
deps =
    myst-parser>=4.0.1
    shibuya>=2024.5.15
    sphinx>=8.2.3
    sphinxcontrib-mermaid>=1.0.0
commands =
    sphinx-build docs/ docs/_build/html -b html
