[tox]
requires = tox>=4.21
env_list = docs, docs-linkcheck
skipsdist = True

[testenv]
deps =
    myst-parser>=4.0.1
    shibuya>=2024.5.15
    sphinx>=8.2.3
    sphinxcontrib-mermaid>=1.0.0

[testenv:docs]
description = Build Sphinx documentation
deps = {[testenv]deps}
commands =
    sphinx-build docs/ docs/_build/html -b html

[testenv:docs-linkcheck]
description = Validate outbound documentation links
deps = {[testenv]deps}
commands =
    sphinx-build docs/ docs/_build/linkcheck -b linkcheck
