#!/usr/bin/env bash

set -euo pipefail

VERSION_RAW="${1:?version required}"
CHECKSUMS="${2:?checksums file required}"
OUT_DIR="${3:?output dir required}"
VERSION="${VERSION_RAW#v}"
REPO="jbcom/get-bashed"
TAG="v${VERSION}"
RELEASE_URL="https://github.com/${REPO}/releases/download/${TAG}"
UNIX_ARCHIVE="get-bashed-${VERSION}-unix.tar.gz"
WINDOWS_ARCHIVE="get-bashed-${VERSION}-windows.zip"

sha_of() {
  local name="$1"
  local sha
  sha="$(grep " ${name}\$" "$CHECKSUMS" | awk '{print $1}')"
  if [ -z "$sha" ]; then
    echo "missing checksum for ${name}" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

SHA_UNIX="$(sha_of "$UNIX_ARCHIVE")"
SHA_WINDOWS="$(sha_of "$WINDOWS_ARCHIVE")"

mkdir -p "$OUT_DIR"

cat >"$OUT_DIR/get-bashed.rb" <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by get-bashed's release pipeline.
# DO NOT EDIT.
class GetBashed < Formula
  desc "Managed Bash environment bootstrap and runtime for macOS, Linux, and WSL"
  homepage "https://github.com/${REPO}"
  url "${RELEASE_URL}/${UNIX_ARCHIVE}"
  sha256 "${SHA_UNIX}"
  version "${VERSION}"
  license "MIT"

  depends_on "bash"

  def install
    stage_dir = Dir["get-bashed-*"].find { |path| File.directory?(path) }
    raise "release bundle missing staged root" unless stage_dir

    libexec.install Dir["#{stage_dir}/*"]
    (bin/"get-bashed").write <<~EOS
      #!/bin/sh
      exec "#{libexec}/install.sh" "\$@"
    EOS
  end

  test do
    system "#{bin}/get-bashed", "--help"
  end
end
EOF

cat >"$OUT_DIR/get-bashed.json" <<EOF
{
  "version": "${VERSION}",
  "description": "Managed Bash environment bootstrap and runtime for macOS, Linux, and WSL",
  "homepage": "https://github.com/${REPO}",
  "license": "MIT",
  "url": "${RELEASE_URL}/${WINDOWS_ARCHIVE}",
  "hash": "${SHA_WINDOWS}",
  "bin": "get-bashed.cmd",
  "architecture": {
    "64bit": {
      "url": "${RELEASE_URL}/${WINDOWS_ARCHIVE}",
      "hash": "${SHA_WINDOWS}"
    }
  },
  "checkver": {
    "github": "https://github.com/${REPO}"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/${REPO}/releases/download/v\$version/get-bashed-\$version-windows.zip"
      }
    }
  }
}
EOF

cat >"$OUT_DIR/get-bashed.nuspec" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>get-bashed</id>
    <version>${VERSION}</version>
    <title>get-bashed</title>
    <authors>Jon B</authors>
    <owners>jbcom</owners>
    <projectUrl>https://github.com/${REPO}</projectUrl>
    <licenseUrl>https://github.com/${REPO}/blob/main/LICENSE</licenseUrl>
    <projectSourceUrl>https://github.com/${REPO}</projectSourceUrl>
    <packageSourceUrl>https://github.com/jbcom/pkgs</packageSourceUrl>
    <docsUrl>https://jbcom.github.io/get-bashed/</docsUrl>
    <bugTrackerUrl>https://github.com/${REPO}/issues</bugTrackerUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <summary>Managed Bash environment bootstrap and runtime for macOS, Linux, and WSL</summary>
    <description>
get-bashed installs a managed Bash profile under ~/.get-bashed, wires shell
startup predictably, keeps installer choices reproducible, and ships Windows
wrapper launchers that invoke the bundled installer through WSL.
    </description>
    <tags>bash shell bootstrap terminal wsl dotfiles cli</tags>
    <releaseNotes>https://github.com/${REPO}/releases/tag/${TAG}</releaseNotes>
  </metadata>
  <files>
    <file src="tools/**" target="tools" />
  </files>
</package>
EOF

cat >"$OUT_DIR/chocolateyInstall.ps1" <<EOF
\$ErrorActionPreference = 'Stop'
\$packageName = 'get-bashed'
\$toolsDir = "\$(Split-Path -Parent \$MyInvocation.MyCommand.Definition)"
\$url64 = '${RELEASE_URL}/${WINDOWS_ARCHIVE}'
\$checksum64 = '${SHA_WINDOWS}'

\$packageArgs = @{
  packageName = \$packageName
  unzipLocation = \$toolsDir
  url64bit = \$url64
  checksum64 = \$checksum64
  checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs
Install-BinFile -Name 'get-bashed' -Path (Join-Path \$toolsDir 'get-bashed.cmd')
EOF

cat >"$OUT_DIR/VERIFICATION.txt" <<EOF
VERIFICATION

get-bashed ${VERSION} for Windows ships as:
  ${RELEASE_URL}/${WINDOWS_ARCHIVE}

Checksum (SHA-256): ${SHA_WINDOWS}

Verify locally on Windows:

  Get-FileHash get-bashed-${VERSION}-windows.zip -Algorithm SHA256

Also verify sigstore build provenance:

  gh attestation verify get-bashed-${VERSION}-windows.zip --owner jbcom
EOF
