apply_gitconfig() {
  local cfg="$PREFIX/gitconfig"

  [[ -r "$cfg" ]] || return 0
  command -v git >/dev/null 2>&1 || return 0

  if [[ -n "$USER_NAME" ]]; then
    git config -f "$cfg" user.name "$USER_NAME"
  fi
  if [[ -n "$USER_EMAIL" ]]; then
    git config -f "$cfg" user.email "$USER_EMAIL"
  fi
}

migrate_legacy() {
  local legacy_rc_d="$HOME/.bashrc.d"
  local legacy_secrets_d="$HOME/.secrets.d"
  local file

  if [[ -d "$legacy_rc_d" && ! -L "$legacy_rc_d" ]]; then
    echo "Migrating legacy .bashrc.d to $PREFIX/bashrc.d..."
    mkdir -p "$PREFIX/bashrc.d"
    while IFS= read -r -d '' file; do
      copy_legacy_file "$file" "$PREFIX/bashrc.d"
    done < <(find "$legacy_rc_d" -type f -print0)
    rm -rf "$legacy_rc_d"
  fi

  if [[ -d "$legacy_secrets_d" && ! -L "$legacy_secrets_d" ]]; then
    echo "Migrating legacy .secrets.d to $PREFIX/secrets.d..."
    mkdir -p "$PREFIX/secrets.d"
    chmod 700 "$PREFIX/secrets.d"
    while IFS= read -r -d '' file; do
      copy_legacy_file "$file" "$PREFIX/secrets.d"
    done < <(find "$legacy_secrets_d" -type f -print0)
    rm -rf "$legacy_secrets_d"
  fi

  for file in "$HOME/.bashrc" "$HOME/.bash_profile"; do
    if [[ -f "$file" && ! -L "$file" ]] &&
      (grep -q "@file bashrc" "$file" || grep -q "@file bash_profile" "$file"); then
      if [[ "$LINK_DOTFILES" -eq 0 ]]; then
        echo "Detected recursive loop hazard in $file. Cleaning..."
        backup_file "$file"
        echo "# get-bashed: recovered from loop" > "$file"
      fi
    fi
  done
}

escape_config_value() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\$/\\\$}"
  value="${value//\"/\\\"}"
  value="${value//\`/\\\`}"
  echo "$value"
}

write_config_file() {
  local escaped

  {
    echo "# Generated by get-bashed installer"
    echo "export GET_BASHED_GNU=${GET_BASHED_GNU}"
    echo "export GET_BASHED_BUILD_FLAGS=${GET_BASHED_BUILD_FLAGS}"
    echo "export GET_BASHED_AUTO_TOOLS=${GET_BASHED_AUTO_TOOLS}"
    echo "export GET_BASHED_SSH_AGENT=${GET_BASHED_SSH_AGENT}"
    echo "export GET_BASHED_USE_DOPPLER=${GET_BASHED_USE_DOPPLER}"
    echo "export GET_BASHED_USE_BASH_IT=${GET_BASHED_USE_BASH_IT}"
    echo "export GET_BASHED_GIT_SIGNING=${GET_BASHED_GIT_SIGNING}"
    echo "export GET_BASHED_VIMRC_MODE=\"${GET_BASHED_VIMRC_MODE}\""
    if [[ -n "$USER_NAME" ]]; then
      escaped="$(escape_config_value "$USER_NAME")"
      echo "export GET_BASHED_USER_NAME=\"${escaped}\""
    fi
    if [[ -n "$USER_EMAIL" ]]; then
      escaped="$(escape_config_value "$USER_EMAIL")"
      echo "export GET_BASHED_USER_EMAIL=\"${escaped}\""
    fi
  } > "$PREFIX/get-bashedrc.sh"
}

write_runtime_pin_file() {
  {
    echo "# Generated by get-bashed installer"
    echo "GET_BASHED_GEMINI_CLI_PACKAGE_SPEC=\"${GET_BASHED_NODE_GLOBAL_PACKAGES["gemini"]}\""
    echo "GET_BASHED_SONAR_SCAN_PACKAGE_SPEC=\"${GET_BASHED_NODE_GLOBAL_PACKAGES["sonar"]}\""
  } > "$PREFIX/get-bashed-pins.sh"
}

wire_shell_startup() {
  local bashrc_line bashrc_snip bash_profile_line bash_profile_snip

  if [[ "$LINK_DOTFILES" -eq 1 ]]; then
    link_dotfile bashrc
    link_dotfile bash_profile
    link_dotfile inputrc
    link_dotfile bash_aliases
    link_dotfile vimrc
    if [[ -n "$USER_NAME" && -n "$USER_EMAIL" ]]; then
      link_dotfile gitconfig
    else
      echo "Skipping gitconfig link (missing --name/--email)." >&2
    fi
    return 0
  fi

  # shellcheck disable=SC2016
  bashrc_line="# get-bashed: source modular bashrc"
  # shellcheck disable=SC2016
  bashrc_snip="if [[ -r \"$PREFIX/bashrc\" ]]; then source \"$PREFIX/bashrc\"; fi"
  bash_profile_line="# get-bashed: source login bash_profile"
  # shellcheck disable=SC2016
  bash_profile_snip="if [[ -r \"$PREFIX/bash_profile\" ]]; then source \"$PREFIX/bash_profile\"; fi"

  ensure_block "$HOME/.bashrc" "$bashrc_line" "$bashrc_snip"
  ensure_block "$HOME/.bash_profile" "$bash_profile_line" "$bash_profile_snip"
}

install_managed_assets() {
  sync_managed_assets
  migrate_legacy
  ensure_secrets_stub
  write_config_file
  write_runtime_pin_file
  apply_gitconfig
  wire_shell_startup
}
