name: Release

on:
  release:
    types: [published]

jobs:
  artifacts:
    name: Upload Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Package
        run: ./scripts/package.sh dist "${GITHUB_REF_NAME}"
      - name: Upload tarball
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8ad5bc06adad52 # v6.0.0
        with:
          files: dist/get-bashed-${{ github.ref_name }}.tar.gz
