name: Release

on:
  release:
    types: [published]

jobs:
  artifacts:
    name: Upload Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Package
        run: ./scripts/package.sh dist "${GITHUB_REF_NAME}"
      - name: Upload tarball
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: dist/get-bashed-${{ github.ref_name }}.tar.gz
